-- Limpar dados antigos da vertical Vistoria de Recebimento
DELETE FROM public.checklist_itens WHERE secao_id IN (SELECT id FROM public.checklist_secoes WHERE categoria='vistoria');
DELETE FROM public.checklist_secoes WHERE categoria='vistoria';

-- Inserir as 9 seções da Vistoria de Recebimento
WITH novas_secoes AS (
  INSERT INTO public.checklist_secoes (numero, titulo, categoria, peso, reincidencia, ordem)
  VALUES
    (1, 'OBRA CIVIL', 'vistoria', 10, 0, 1),
    (2, 'INSTALAÇÕES ELÉTRICAS', 'vistoria', 10, 0, 2),
    (3, 'AR-CONDICIONADO E VENTILAÇÃO MECÂNICA', 'vistoria', 10, 0, 3),
    (4, 'DETECÇÃO, ALARME E COMBATE A INCÊNDIO', 'vistoria', 10, 0, 4),
    (5, 'HIDRÁULICA', 'vistoria', 10, 0, 5),
    (6, 'AUTOMAÇÃO PREDIAL / BMS', 'vistoria', 10, 0, 6),
    (7, 'CONTROLE DE ACESSO E CFTV', 'vistoria', 10, 0, 7),
    (8, 'LUMINÁRIAS', 'vistoria', 10, 0, 8),
    (9, 'DOCUMENTAÇÃO A SOLICITAR / OUTROS', 'vistoria', 10, 0, 9)
  RETURNING id, numero
)
INSERT INTO public.checklist_itens (secao_id, codigo, descricao, ordem)
SELECT s.id, x.codigo, x.descricao, x.ordem
FROM novas_secoes s
JOIN (VALUES
  -- 1. OBRA CIVIL
  (1, '1.01', 'Hall de elevadores', 1),
  (1, '1.02', 'Porta de entrada (vidro)', 2),
  (1, '1.03', 'Copa', 3),
  (1, '1.04', 'Forro removível', 4),
  (1, '1.05', 'Esquadrias', 5),
  (1, '1.06', 'Sanitários (louças, metais, bancadas, divisórias)', 6),
  (1, '1.07', 'Paredes (acabamento, integridade, pintura)', 7),
  (1, '1.08', 'Paredes do "core" – alinhamento, nível e prumo', 8),
  (1, '1.09', 'Escada', 9),
  (1, '1.10', 'Piso elevado', 10),
  (1, '1.11', 'Persianas', 11),
  (1, '1.12', 'Carpete', 12),
  (1, '1.13', 'Avarias em paredes / revestimentos', 13),
  -- 2. INSTALAÇÕES ELÉTRICAS
  (2, '2.01', 'Capacidade do disjuntor de entrada', 1),
  (2, '2.02', 'Medição de energia (concessionária)', 2),
  (2, '2.03', 'Lacre da concessionária', 3),
  (2, '2.04', 'Caixa do quadro elétrico de distribuição (integridade)', 4),
  (2, '2.05', 'Identificação e proteção conforme NR-10 (avisos de advertência)', 5),
  (2, '2.06', 'Protetor contra surtos (DPS)', 6),
  (2, '2.07', 'Barramentos', 7),
  (2, '2.08', 'Aterramento (inclusive porta dos quadros)', 8),
  (2, '2.09', 'IDR (DR) para áreas molhadas', 9),
  (2, '2.10', 'Etiquetas adesivas de advertência e tensão (NR-10)', 10),
  (2, '2.11', 'Infra de alimentador principal', 11),
  (2, '2.12', 'Infraestruturas reaproveitadas', 12),
  (2, '2.13', 'Eletrocalhas', 13),
  (2, '2.14', 'Eletrodutos', 14),
  (2, '2.15', 'Cabo alimentador – isolamento (mín. 0,6/1 kV)', 15),
  (2, '2.16', 'Cabos reaproveitados', 16),
  (2, '2.17', 'Tipo de cabeamento (450/750 V ou 0,6/1 kV)', 17),
  (2, '2.18', 'Terminais nas extremidades dos cabos alimentadores', 18),
  (2, '2.19', 'Anilhas de identificação de fases (R, S, T)', 19),
  (2, '2.20', 'Características antichama / atóxico / baixa emissão de fumaça (LSZH)', 20),
  (2, '2.21', 'Transformadores reaproveitados', 21),
  (2, '2.22', 'Nobreaks reaproveitados', 22),
  (2, '2.23', 'Luminárias reaproveitadas (substituição de fluorescentes por LED)', 23),
  (2, '2.24', 'GMG reaproveitado', 24),
  (2, '2.25', 'Estabilizadores reaproveitados', 25),
  (2, '2.26', 'Acionamento de iluminação (interruptores / automação)', 26),
  -- 3. AR-CONDICIONADO E VENTILAÇÃO MECÂNICA
  (3, '3.01', 'Bombas primárias – inspeção visual e teste', 1),
  (3, '3.02', 'Bombas secundárias – inspeção visual e teste', 2),
  (3, '3.03', 'Chiller – inspeção visual e teste', 3),
  (3, '3.04', 'Filtros e registros das bombas', 4),
  (3, '3.05', 'Manômetros e termômetros', 5),
  (3, '3.06', 'Chave de fluxo', 6),
  (3, '3.07', 'Variador de frequência (VFD) na bomba secundária', 7),
  (3, '3.08', 'Transdutor de pressão – teste de variação da bomba secundária', 8),
  (3, '3.09', 'Tubulação de by-pass com válvula motorizada', 9),
  (3, '3.10', 'Fan-Coil – inspeção visual e teste funcional', 10),
  (3, '3.11', 'Válvulas de 2 ou 3 vias do Fan-Coil', 11),
  (3, '3.12', 'Posição do sensor de pressão', 12),
  (3, '3.13', 'Posição do sensor de temperatura', 13),
  (3, '3.14', 'Fancoletes – inspeção visual e teste', 14),
  (3, '3.15', 'Válvulas de 2 ou 3 vias dos fancoletes', 15),
  (3, '3.16', 'Termostatos (com atuação no BMS)', 16),
  (3, '3.17', 'Sistema de tratamento de água', 17),
  (3, '3.18', 'Torre de resfriamento – inspeção visual e teste', 18),
  (3, '3.19', 'Registros e boia de nível', 19),
  (3, '3.20', 'Bomba de água de condensação – inspeção visual e teste', 20),
  (3, '3.21', 'Bomba de recirculação', 21),
  (3, '3.22', 'Self condensação a água – ΔT mínimo de 8 °C', 22),
  (3, '3.23', 'Chave de fluxo (condensação)', 23),
  (3, '3.24', 'Condensador a água – inspeção visual e teste', 24),
  (3, '3.25', 'Condensadora VRF – inspeção visual e teste', 25),
  (3, '3.26', 'Disjuntor individual para cada condensadora', 26),
  (3, '3.27', 'Evaporadoras / recuperador de calor – quantidade e capacidade', 27),
  (3, '3.28', 'Evaporadoras / recuperadores – inspeção visual e teste', 28),
  (3, '3.29', 'Filtros de ar dos evaporadores (G4 + F5 conforme NBR 16401)', 29),
  (3, '3.30', 'Bomba de dreno ou dreno por gravidade – teste', 30),
  (3, '3.31', 'Comunicação (rede de controle)', 31),
  (3, '3.32', 'Controle remoto centralizado', 32),
  (3, '3.33', 'Termostato VRF', 33),
  (3, '3.34', 'Estado das aletas das serpentinas das condensadoras', 34),
  (3, '3.35', 'Condensadora Split – inspeção visual e teste', 35),
  (3, '3.36', 'Evaporadora Split – inspeção visual e teste', 36),
  (3, '3.37', 'Controle remoto sem fio', 37),
  (3, '3.38', 'Linha frigorígena – suportação e isolamento', 38),
  (3, '3.39', 'Interligação de dreno', 39),
  (3, '3.40', 'Casa de máquinas com atenuador de ruído (insuflação e retorno)', 40),
  (3, '3.41', 'Rede de dutos – integridade, suportação, isolamento e estanqueidade', 41),
  (3, '3.42', 'Damper de regulagem / caixas VAC nos ramais', 42),
  (3, '3.43', 'Damper corta-fogo com elo fusível – teste de fechamento manual', 43),
  (3, '3.44', 'Damper corta-fogo com solenoide interligado ao SDAI', 44),
  (3, '3.45', 'Damper motorizado – testes', 45),
  (3, '3.46', 'Caixas VAV – transformador / atenuador', 46),
  (3, '3.47', 'Caixas VAV – termostato', 47),
  (3, '3.48', 'Bocas de ar / difusores – integridade', 48),
  (3, '3.49', 'Dutos de extração de fumaça isolados com manta cerâmica', 49),
  (3, '3.50', 'Suportes dos dutos em chapa preta com cantoneira e manta cerâmica', 50),
  (3, '3.51', 'Tomada de ar externo (filtragem G4 + F5 conforme NBR 16401)', 51),
  (3, '3.52', 'Isolamento térmico com proteção mecânica em alumínio liso', 52),
  (3, '3.53', 'Casa de máquinas com isolamento acústico nas paredes', 53),
  (3, '3.54', 'Drenagem da casa de máquinas (sem condensação acumulada no piso)', 54),
  (3, '3.55', 'Ventiladores de ar externo – inspeção visual e teste (G4 + F5)', 55),
  (3, '3.56', 'Exaustores de banheiro – inspeção visual e teste', 56),
  (3, '3.57', 'Sistema de extração de fumaça – inspeção visual e teste', 57),
  (3, '3.58', 'Roda entálpica – inspeção visual e teste', 58),
  -- 4. DETECÇÃO, ALARME E COMBATE A INCÊNDIO
  (4, '4.01', 'Caixas de hidrante – quantidade e completas', 1),
  (4, '4.02', 'Mangueiras dentro da validade e teste hidrostático', 2),
  (4, '4.03', 'Esguicho regulável', 3),
  (4, '4.04', 'Chave Storz', 4),
  (4, '4.05', 'Adaptador no bocal', 5),
  (4, '4.06', 'Rede de sprinklers (SPK)', 6),
  (4, '4.07', 'Válvulas setoriais', 7),
  (4, '4.08', 'Pressão da rede', 8),
  (4, '4.09', 'Extintores de água (H₂O) – pressão e validade', 9),
  (4, '4.10', 'Extintores de CO₂ – pressão e validade', 10),
  (4, '4.11', 'Extintores de pó químico – pressão e validade', 11),
  (4, '4.12', 'Tubulação identificada', 12),
  (4, '4.13', 'Aspersores – integridade', 13),
  (4, '4.14', 'Carga nos cilindros', 14),
  (4, '4.15', 'Solenoide', 15),
  (4, '4.16', 'Botoeiras e sirenes', 16),
  (4, '4.17', 'Painel dedicado', 17),
  (4, '4.18', 'Detectores', 18),
  (4, '4.19', 'Teste simulado, com acompanhamento da manutenção, sem disparo do gás', 19),
  (4, '4.20', 'Painel central de incêndio', 20),
  (4, '4.21', 'Detectores óticos de fumaça (endereçáveis ou convencionais)', 21),
  (4, '4.22', 'Detectores termovelocimétricos', 22),
  (4, '4.23', 'Sirenes', 23),
  (4, '4.24', 'Acionadores manuais', 24),
  (4, '4.25', 'Sistema Door Holder (retentor de portas)', 25),
  (4, '4.26', 'Módulos do SDAI (hall, áreas comuns)', 26),
  (4, '4.27', 'Portas corta-fogo', 27),
  -- 5. HIDRÁULICA
  (5, '5.01', 'Vistoria visual da prumada', 1),
  (5, '5.02', 'Ralos', 2),
  (5, '5.03', 'Verificação da ventilação (coluna de ventilação)', 3),
  (5, '5.04', 'Bomba de esgoto – inspeção visual e teste', 4),
  (5, '5.05', 'Hidrômetro', 5),
  (5, '5.06', 'Registro principal – integridade', 6),
  (5, '5.07', 'Suportação', 7),
  (5, '5.08', 'Identificação', 8),
  (5, '5.09', 'Material da tubulação (cobre, PEX, PPR etc.)', 9),
  (5, '5.10', 'Hidrômetro de reuso', 10),
  (5, '5.11', 'Registro principal de reuso – integridade', 11),
  (5, '5.12', 'Suportação reuso', 12),
  (5, '5.13', 'Identificação reuso', 13),
  (5, '5.14', 'Teste dos pontos atendidos (fechando o registro de água fria)', 14),
  (5, '5.15', 'Verificação da prumada dedicada de dreno', 15),
  (5, '5.16', 'Caimento da rede', 16),
  (5, '5.17', 'Suportação dreno', 17),
  (5, '5.18', 'Isolamento', 18),
  -- 6. BMS
  (6, '6.01', 'Tela gráfica do sistema HVAC', 1),
  (6, '6.02', 'Status de todas as VAVs', 2),
  (6, '6.03', 'Status de todas as evaporadoras', 3),
  (6, '6.04', 'Status de todos os sensores (temperatura, pressão, CO₂)', 4),
  (6, '6.05', 'Status de temperatura de todos os termostatos', 5),
  (6, '6.06', 'Comando liga/desliga remoto', 6),
  (6, '6.07', 'Status do variador de frequência (VFD)', 7),
  (6, '6.08', 'Status das válvulas (2 ou 3 vias)', 8),
  (6, '6.09', 'Tela gráfica dos medidores eletrônicos de energia', 9),
  (6, '6.10', 'Tela gráfica dos hidrômetros (água potável e reuso)', 10),
  (6, '6.11', 'Comunicação do laço', 11),
  (6, '6.12', 'Status dos detectores de fumaça', 12),
  (6, '6.13', 'Comunicação da central com as subcentrais', 13),
  (6, '6.14', 'Capacidade de novos detectores (expansão)', 14),
  (6, '6.15', 'Tipo de laço (classe A ou B)', 15),
  -- 7. CONTROLE DE ACESSO E CFTV
  (7, '7.01', 'Sistema de controle de acesso – condições gerais', 1),
  (7, '7.02', 'Dispositivos de controle de acesso instalados / a serem retirados', 2),
  (7, '7.03', 'CFTV – câmeras, gravador (DVR/NVR) e cabeamento', 3),
  (7, '7.04', 'Integração com a portaria / segurança do condomínio', 4),
  -- 8. LUMINÁRIAS
  (8, '8.01', 'Luminárias funcionais – tipo de lâmpada (LED, fluorescente)', 1),
  (8, '8.02', 'Luminárias decorativas – condições gerais', 2),
  (8, '8.03', 'Acionamento (manual por interruptor ou automatizado)', 3),
  (8, '8.04', 'Iluminação de emergência', 4),
  -- 9. DOCUMENTAÇÃO
  (9, '9.01', 'Relatório da central de incêndio – confirmação da comunicação com periféricos', 1),
  (9, '9.02', 'Confirmação de capacidade de expansão da central de incêndio para os andares vistoriados', 2),
  (9, '9.03', 'Relatório do supervisório – comunicação e comando do Fan-Coil (VFD, válvula 3 vias, filtro sujo) e termostatos', 3),
  (9, '9.04', 'Relatórios de testes de performance do sistema VRF (Daikin, Midea etc.)', 4),
  (9, '9.05', 'Relatórios de testes de performance dos equipamentos hidrônicos (fancoletes)', 5),
  (9, '9.06', 'Relatórios de manutenção dos equipamentos VRF, fancoletes e Fan-Coil', 6),
  (9, '9.07', 'Relatório de termografia dos quadros elétricos', 7),
  (9, '9.08', 'Relatório de inspeção visual e reaperto de parafusos', 8),
  (9, '9.09', 'Outros (campo livre)', 9)
) AS x(secao_numero, codigo, descricao, ordem) ON x.secao_numero = s.numero;